export const ACCOUNT_MANAGEMENT_TOKENS = {
	BANK_ACCOUNT_REPOSITORY: Symbol.for('BANK_ACCOUNT_REPOSITORY'),
	BANK_ACCOUNT_READER: Symbol.for('BANK_ACCOUNT_READER'),
	ADD_BANK_ACCOUNT_COMMAND_HANDLER: Symbol.for('ADD_BANK_ACCOUNT_COMMAND_HANDLER'),
	REMOVE_BANK_ACCOUNT_COMMAND_HANDLER: Symbol.for('REMOVE_BANK_ACCOUNT_COMMAND_HANDLER'),
	GET_ALL_BANK_ACCOUNT_QUERY_HANDLER: Symbol.for('GET_ALL_BANK_ACCOUNT_QUERY_HANDLER'),
};
